package form;

public enum FormDBFields {
	TIMESTAMP("TIMESTAMP"),
	FNAME("FNAME"),
	MOVE_REASON("MOVE_REASON"),
	CURRENT_LOC("CURRENT_LOC"),
	MOVE_DATE("MOVE_DATE"),
	HOUSING_TYPE("HOUSING_TYPE"),
	BEDS("BEDS"),
	BATHS("BATHS"),
	WORK_ZIP("WORK_ZIP"),
	WORK_ZIP_2("WORK_ZIP_2"),
	COMMUTE_TIME("COMMUTE_TIME"),
	TRANS_MODE("TRANS_MODE"),
	DESIRED_LOCS("DESIRED_LOCS"),
	DESIRED_REGION("DESIRED_REGION"),
	RENT_OR_BUY("RENT_OR_BUY"),
	EMAIL("EMAIL"),
	PROMO_CODE("PROMO_CODE"),
	PRICE_RANGE_BUY("PRICE_RANGE_BUY"),
	MONTHLY_MORTGAGE("MONTHLY_MORTGAGE"),
	DOWN_PAYMENT("DOWN_PAYMENT"),
	NEEDS_SCHOOL("NEEDS_SCHOOL"),
	MONTHLY_RENT("MONTHLY_RENT"),
	NEEDS_PARKING("NEEDS_PARKING"),
	SCHOOL_LEVEL("SCHOOL_LEVEL"),
	SCHOOL_TYPE("SCHOOL_TYPE"),
	MORE_QUESTIONS("MORE_QUESTIONS"),
	CURRENT_LOC_LIKES_DISLIKES("CURRENT_LOC_LIKES_DISLIKES"),
	IMPORTANT_ACTIVITIES("IMPORTANT_ACTIVITIES"),
	IMPORTANT_AREAS("IMPORTANT_AREAS"),
	WALKABILITY("WALKABILITY"),
	GREENSPACE("GREENSPACE"),
	RESTAURANTS("RESTAURANTS"),
	BARS("BARS"),
	AMENITIES("AMENITIES"),
	SAFETY("SAFETY"),
	ADDTIONAL_INFO("ADDTIONAL_INFO"),
	PREVIOUS_SEARCH("PREVIOUS_SEARCH"),
	APT_STYLE("APT_STYLE"),
	SCHOOL_PERFORMANCE("SCHOOL_PERFORMANCE"),
	PHONE("PHONE"),
	SUMMARY("SUMMARY"),
	ASSIGNED("ASSIGNED"),
	COMMENT("COMMENT"),
	STATUS("STATUS"),
	HAND_OFF_DATE("HAND_OFF_DATE"),
	MATCHED_AREAS("MATCHED_AREAS");
	
	private String info;
	
	private FormDBFields(String s) {
		info = s;
	}
	
	public String toString() {
		return info;
	}
}
